[pytest]
addopts = --strict-markers
markers =
    lento: teste que leva alguns segundos para rodar
    rapido: teste rapido
    crianca: faixa de idade crianca
    adolescente: faixa de idade adolescente
    adulto: faixa de idade adulto
    idoso: faixa de idade idoso
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
